# Generated by Django 4.2.30 on 2026-08-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(default='LedgerVoice Store', max_length=100),
        ),
    ]
