# Generated by Django 6.0.7 on 2026-08-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='upi_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
