# Generated by Django 6.0.7 on 2026-08-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_usersettings_upi_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
