# Generated by Django 4.2.30 on 2026-08-16 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('litre', 'Litre'), ('ml', 'Millilitre'), ('pcs', 'Piece'), ('dozen', 'Dozen'), ('packet', 'Packet'), ('box', 'Box'), ('bag', 'Bag'), ('bundle', 'Bundle'), ('mtr', 'Metre'), ('ft', 'Feet')], default='pcs', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product_name'],
                'unique_together': {('user', 'product_name')},
            },
        ),
    ]
