# Generated by Django 6.0.7 on 2026-08-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='items_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
